openapi: 3.1.0
info:
  title: Plant Database API - Minimal Test
  description: Ultra-minimal schema to test POST functionality
  version: 1.0.0
servers:
  - url: https://dev-plant-database-api.onrender.com
    description: Development server

paths:
  /api/health:
    get:
      operationId: testHealthGet
      summary: Test GET endpoint
      description: Working GET endpoint for comparison
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /api/test/minimal-post:
    post:
      operationId: testMinimalPost
      summary: Test POST endpoint
      description: Ultra-minimal POST test
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string